### ISSUE TITLE
can't find utils/scripts/runner.sh

### ISSUE THREAD

**Issue by PALIN2018** [tdopierre/FewShotText#2]
Hi！Your paper is interesting and I could not wait to reproduce the results in your paper. But I can not find the runner.sh. So could you please upload it to the corresponding directory? Thx!

**Comment by tdopierre** [comment]
Hello, 
I added the `utils/scripts/runner.sh` script which reproduces the paper's results. 
Please note it was made to be run in the `slurm` job manager, because there are a lot of experiments. 
To run it without slurm, replace the `sbatch` commands with the `models/<model>/<model>.sh` commands.
